version: '3'
services:
  redis3:
    image: redis:7.4.2-alpine3.21
    container_name: redis3
    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes", "--port", "7002"]
    ports:
      - "7002:7002"
      - "17002:17002"
    volumes:
      - ./data3:/data
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge
