
services:
  haproxy:
    image: haproxy:2.9
    container_name: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "6379:6379"
      - "8000:8000" # HAProxy stats
    # networks:
    #   - redis-net
  