version: '3.8'
services:
  redis-master:
    build: .
    container_name: redis-master
    # ports:
    #   - "6379:6379"
    volumes:
      - ./data/redis-master:/data
    networks:
      - reddis

  redis-slave-1:
    build: .
    container_name: redis-slave-1
    # ports:
    #   - "6380:6379"
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT=6379
    networks:
      - reddis

  redis-slave-2:
    build: .
    container_name: redis-slave-2
    # ports:
    #   - "6381:6379"
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT=6379
    networks:
      - reddis

  sentinel-1:
    image: redis:6.0-alpine
    container_name: sentinel-1
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel/sentinel-1.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      - reddis
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2

  sentinel-2:
    image: redis:6.0-alpine
    container_name: sentinel-2
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
    ports:
      - "26380:26380"
    volumes:
      - ./sentinel/sentinel-2.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      - reddis
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2

  sentinel-3:
    image: redis:6.0-alpine
    container_name: sentinel-3
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
    ports:
      - "26381:26381"
    volumes:
      - ./sentinel/sentinel-3.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      - reddis
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
  
  haproxy:
    image: haproxy:2.4
    container_name: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "6379:6379"
      - "8000:8000"
    networks:
      - reddis
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2

networks:
    reddis:
        external: true
        name: reddis

