version: '3'
services:
  redis-replica:
    image: redis:7.4.2-alpine3.21
    container_name: redis-replica
    ports:
      - "6379:6379"
    command: redis-server --replicaof 192.168.173.107 6379
  
  redis-sentinel:
    image: redis:7.4.2-alpine3.21
    container_name: redis-sentinel
    ports:
      - "26379:26379"
    command: >
      redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - ./sentinel.conf:/etc/redis/sentinel.conf
