version: '3.9'
services:
  redis-master:
    image: redis:7.4.2-alpine3.21
    container_name: redis-master
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - app_net

  redis-replica:
    image: redis:7.4.2-alpine3.21
    container_name: redis-replica
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes --replicaof redis-master 6379
    networks:
      - app_net

  sentinel:
    image: redis:7.4.2-alpine3.21
    container_name: redis-sentinel
    depends_on:
      - redis-master
    ports:
      - "26379:26379"
    command: >
      redis-sentinel /etc/sentinel.conf
    volumes:
      - ./sentinel.conf:/etc/sentinel.conf
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
