services:
    myredis:
        container_name: 'redis'
        image: redis:7.4.2-alpine3.21
        healthcheck:
            test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - ./data:/data
        command: redis-server --stop-writes-on-bgsave-error no
        networks:
            - app_net
